name: "Setup Python Environment"
description: "Install Python, uv, and sync dependencies"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.12"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.6.2"
  working-directory:
    description: "Directory that contains pyproject.toml"
    required: false
    default: "."
  uv_extra_packages:
    description: "Extra packages to install with uv"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: "true"
        cache-suffix: ${{ inputs.python-version }}

    - name: Install Python dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: uv sync --frozen ${{ inputs.uv_extra_packages }}
